apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spider26-regapp
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: public.ecr.aws/g9s4l3g0/argocd:13
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: app1-nginx
spec:
  type: NodePort
  selector:
    app: regapp
  ports:
    - port: 80
      targetPort: 8080
